ClassOf2021Site/ClassOf2021Site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contact/', include('contact.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('pictures/', include('pictures.urls')),
    path('dues/', include('dues.urls')),
    path('events/', include('events.urls')),
    path('important/', include('important.urls')),
]

ClassOf2021Site/contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'
urlpatterns = [
    path('', views.index, name="home"),
]

ClassOf2021Site/dues/urls.py
from django.urls import path, include
from . import views

app_name = 'dues'
urlpatterns = [
    path('', views.index, name='index'),
]

ClassOf2021Site/events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name="index"),
]

ClassOf2021Site/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('announcements/', views.announcements, name='announcements'),
]

ClassOf2021Site/important/urls.py
from django.urls import path, include
from . import views

app_name = 'important'
urlpatterns = [
    path('', views.index, name='index'),
]

ClassOf2021Site/pictures/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pictures'

urlpatterns = [
    path('', views.index, name='index'),
]

ClassOf2021Site/home/models.py
from django.db import models

# Create your models here.

class Announcement(models.Model):
    title_text = models.CharField("Title", max_length=200)
    pub_date = models.DateTimeField("Date published", help_text="Click 'Today' and 'Now'")
    body_text = models.CharField(max_length=1000)

    def __str__(self):
        return self.title_text

    class Meta():
        verbose_name = 'Announcement'

ClassOf2021Site/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Announcement

# Create your views here.

def index(request):
    latest_announcements = Announcement.objects.order_by('-pub_date')[:4]
    context = {
        'latest_announcements' : latest_announcements,
    }
    return render(request, 'home/index.html', context)

def announcements(request):
    latest_announcements_all = Announcement.objects.order_by('-pub_date')[:]
    context = {
        'latest_announcements_all' : latest_announcements_all,
    }
    return render(request, 'home/announcements.html', context)

ClassOf2021Site/home/templates/home/announcements.html
<head>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen and (min-width: 900px)" href="{% static 'home/styleWide.css' %}">
    <link rel="stylesheet" type="text/css" media="screen and (max-width: 900px)" href="{% static 'home/styleMobile.css' %}">
</head>

<title>Announcements</title>


<div class="button">
    <a href="{% url 'home:index' %}" id="back">
        <span id="home">
            <i class="fas fa-chevron-left"></i> Back
        </span>
    </a>
</div>

<div class="announcements2">
    <div class="announcements0">
        Announcements
    </div>
</div>

<div class="main">
    <div class="announcementArea">
        {% if latest_announcements_all %}
                <div>
                {% for announcement in latest_announcements_all %}
                <br>
                    <div id="announcementBlock">
                        <h2>
                            {{ announcement.title_text }}
                        </h2>
                        <p id="pub_date">
                            {{ announcement.pub_date }}
                        </p>
                        <p>
                            {{ announcement.body_text }}
                        </p>
                    </div>
                    <br>
                {% endfor %}
                </div>
        {% else %}
            <div>
                <p>We have no current announcements.</p>
            </div>
        {% endif %}
    </div>
</div>

ClassOf2021Site/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen and (min-width: 900px)" href="{% static 'home/styleWide.css' %}">
    <link rel="stylesheet" type="text/css" media="screen and (max-width: 900px)" href="{% static 'home/styleMobile.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Shepherd Hill Class of 2021</title>
</head>
<body>
    {% load socialaccount %}
    {% if user.is_authenticated %}
    <header>
        <div>
            <img src="{% static 'home/Ram.jpg' %}" alt="ram" class="RamImageLeft">
        </div>
        <div>
            <p class="title">Shepherd Hill Class of 2021</p>
        </div>
        <div>
            <img src="{% static 'home/Ram.jpg' %}" alt="ram" class="RamImageRight">
        </div>
    </header>
    <div class="box">
        <div id="a"><p>Hi, {{ user.username }}</p></div>
        <div id="b"><a href="{% url 'logout' %}">Log out <i class="fas fa-sign-out-alt"></i></a></div>
    </div>
    <nav>
        <ul>
            <li><a href="{% url 'contact:home' %}">Contact Your Officers</a></li>
            <li><a href="{% url 'pictures:index' %}">Pictures</a></li>
            <li><a href="{% url 'dues:index' %}">My Dues</a></li>
            <li><a href="{% url 'events:index' %}">Calendar</a></li>
            <li><a href="{% url 'important:index' %}">Important Events</a></li>
        </ul>
    </nav>
    <section>
        <div class="announcements1">
            <div class="announcements">
                Announcements
            </div>
        </div>
        <div class="main">
            <div>
                <div class="announcementArea">
                    <!-- Announcements -->
                    {% if latest_announcements %}
                    <br>
                        <div>
                        {% for announcement in latest_announcements %}
                            <div id="announcementBlock">
                                <h2 id="title">
                                    {{ announcement.title_text }}
                                </h2>
                                <p id="pub_date">
                                    {{ announcement.pub_date }}
                                </p>
                                <p id="body">
                                    {{ announcement.body_text }}
                                </p>
                            </div>
                            <br>
                        {% endfor %}
                        </div>
                    {% else %}
                        <div>
                            <p>We have no current announcements.</p>
                        </div>
                    {% endif %}
                    <a href="{% url 'home:announcements' %}" id="announcementsLink">View all announcements <i class="fas fa-chevron-right"></i></a>
                </div>
            </div>
            <div class="twitter">
                <a class="twitter-timeline" data-width="280" data-height="676" data-link-color="#800000" href="https://twitter.com/SHClassOf2021?ref_src=twsrc%5Etfw">Tweets by SHClassOf2021</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
        </div>
    </section>
    {% else %}
    <header>
        <div>
            <img src="{% static 'home/Ram.jpg' %}" alt="ram" class="RamImageLeft">
        </div>
        <div>
            <p class="title">Shepherd Hill Class of 2021</p>
        </div>
        <div>
            <img src="{% static 'home/Ram.jpg' %}" alt="ram" class="RamImageRight">
        </div>
    </header>
    <a href="{% provider_login_url 'google' %}" id="loginLink">
        <div class="loginButton">
            <span class="GoogleButton">
                    <img id="logo" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
                     Login with Google
            </span>
        </div>
    </a>
    {% endif %}
</body>
</html>